stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: gradle:6.0.1-jdk8
          shellScript: |-
            gradle clean build
  - name: Publish
    steps:
        - publishImageConfig:
            dockerfilePath: ./Dockerfile
            buildContext: .
            tag: ayu_dag_backend:1.1.1
#  - name: Deploy
#    steps:
#        - applyYamlConfig:
#          path: ./deployment.yaml

#  - name: Publish my image
#      steps:
#        - publishImageConfig:
#            dockerfilePath: ./Dockerfile
#            buildContext: .
#            tag: rancher/rancher:v2.0.0