stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: gradle:6.0.1-jdk8
          shellScript: |-
            gradle clean build
  - name: Publish
    steps:
        - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: example-greenhouse:1.1.1
#  - name: Deploy
#    steps:
#        - applyYamlConfig:
#          path: ./deployment.yaml

