kind: Service
apiVersion: v1
metadata:
  name: ayu-dag-backend-service
spec:
  selector:
    app: ayu-dag-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ayu-dag-backend
  labels:
    app: ayu-dag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayu-dag-backend
  template:
    metadata:
      labels:
        app: ayu-dag-backend
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080