package ru.ayu_dag.backend.model;

import lombok.Data;

import javax.persistence.*;

@Data
@Entity
@Table(name = "address")
public class Address {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "postal_code")
    private String postalCode;
    private String country;
    @Column(name = "country_iso_code")
    private String countryIsoCode;
    @Column(name = "federal_district")
    private String federalDistrict;
    @Column(name = "region_fias_id")
    private String regionFiasId;
    @Column(name = "region_kladr_id")
    private String regionKladrId;
    @Column(name = "region_iso_code")
    private String regionIsoCode;
    @Column(name = "region_with_type")
    private String regionWithType;
    @Column(name = "region_type")
    private String regionType;
    @Column(name = "region_type_full")
    private String regionTypeFull;
    private String region;
    @Column(name = "area_fias_id")
    private String areaFiasId;
    @Column(name = "area_kladr_id")
    private String areaKladrId;
    @Column(name = "area_with_type")
    private String areaWithType;
    @Column(name = "area_type")
    private String areaType;
    @Column(name = "area_type_full")
    private String areaTypeFull;
    private String area;
    @Column(name = "city_fias_id")
    private String cityFiasId;
    @Column(name = "city_kladr_id")
    private String cityKladrId;
    @Column(name = "city_with_type")
    private String cityWithType;
    @Column(name = "city_type")
    private String cityType;
    @Column(name = "city_type_full")
    private String cityTypeFull;
    private String city;
    @Column(name = "city_area")
    private String cityArea;
    @Column(name = "city_district_fias_id")
    private String cityDistrictFiasId;
    @Column(name = "city_district_kladr_id")
    private String cityDistrictKladrId;
    @Column(name = "city_district_with_type")
    private String cityDistrictWithType;
    @Column(name = "city_district_type")
    private String cityDistrictType;
    @Column(name = "city_district_type_full")
    private String cityDistrictTypeFull;
    @Column(name = "city_district")
    private String cityDistrict;
    @Column(name = "settlement_fias_id")
    private String settlementFiasId;
    @Column(name = "settlement_kladr_id")
    private String settlementKladrId;
    @Column(name = "settlement_with_type")
    private String settlementWithType;
    @Column(name = "settlement_type")
    private String settlementType;
    @Column(name = "settlement_type_full")
    private String settlementTypeFull;
    private String settlement;
    @Column(name = "street_fias_id")
    private String streetFiasId;
    @Column(name = "street_kladr_id")
    private String streetKladrId;
    @Column(name = "street_with_type")
    private String streetWithType;
    @Column(name = "street_type")
    private String streetType;
    @Column(name = "street_type_full")
    private String streetTypeFull;
    private String street;
    @Column(name = "house_fias_id")
    private String houseFiasId;
    @Column(name = "house_kladr_id")
    private String houseKladrId;
    @Column(name = "house_type")
    private String houseType;
    @Column(name = "house_type_full")
    private String houseTypeFull;
    private String house;
    @Column(name = "block_type")
    private String blockType;
    @Column(name = "block_type_full")
    private String blockTypeFull;
    private String block;
    @Column(name = "flat_type")
    private String flatType;
    @Column(name = "flat_type_full")
    private String flatTypeFull;
    private String flat;
    @Column(name = "flat_area")
    private Double flatArea;
    @Column(name = "square_meter_price")
    private Double squareMeterPrice;
    @Column(name = "flat_price")
    private Double flatPrice;
    @Column(name = "postal_box")
    private String postalBox;
    @Column(name = "fias_id")
    private String fiasId;
    @Column(name = "fias_code")
    private String fiasCode;
    @Column(name = "fias_level")
    private String fiasLevel;
    @Column(name = "fias_actuality_state")
    private String fiasActualityState;
    @Column(name = "kladr_id")
    private String kladrId;
    @Column(name = "geoname_id")
    private String geonameId;
    @Column(name = "capital_marker")
    private String capitalMarker;
    private String okato;
    private String oktmo;
    @Column(name = "tax_office")
    private String taxOffice;
    @Column(name = "tax_office_legal")
    private String taxOfficeLegal;
    @Column(name = "geo_lat")
    private Double geoLat;
    @Column(name = "geo_lon")
    private Double geoLon;
    @Column(name = "beltway_hit")
    private String beltwayHit;
    @Column(name = "beltway_distance")
    private Double beltwayDistance;
    @Column(name = "qc_geo")
    private String qcGeo;
    @Column(name = "qc_complete")
    private String qcComplete;
    @Column(name = "qc_house")
    private String qcHouse;
    @Column(name = "unparsed_parts")
    private String unparsedParts;
    private String source;
    private String qc;
    @OneToOne(mappedBy = "address", cascade = CascadeType.ALL,
            fetch = FetchType.LAZY, optional = false)
    private Hotel hotel;
}
